QuakeMigrate/QuakeMigrate

QMigrate/core/model.py

Added a function that sweeps a NLLOC 2D travel time grid across a 3D grid to generate the 3D TT LUT.
renamed compute_1d_vmodel to compute_1d_vmodel_skfmm

feat(core.model.py): add 1d TT sweep

---

example_running_scripts/Detect.py
example_running_scripts/Trigger.py
example_running_scripts/create_lut.py

Added a folder containing example running scripts to the repository

feat(example_running_scripts): added example scripts

---

QMigrate/core/model.py

Corrected function _update_grid_centre() in class NonLinLoc;
transform had projections the wrong way around to calculate grid centre
coordinates, meaning read_3d_nlloc_lut() did not work.

fix(core/model.py): Fix NLLoc proj

---

QMigrate/signal/scan.py

The video function now correctly generates an mp4 file that depicts the
coalescence through time.

fix(signal/scan.py): fix video feature

---

QMigrate/core/model.py

Adjust new compute_1d_vmodel() to comply with PEP8 guidelines.

style(core/model.py): PEP8 compliance

---

QMigrate/core/model.py

Fixed a bug such that a when a stations Z coordinate was not contained within the final required grid nlloc threw an error
closed issue #8

fix(core/model.py): fixed station Z not in NLLOC grid

---

QMigrate/core/model.py

fixed an error in the vgradient function that threw an error when calculating gradient velocity models

fix(core/model.py) vgradient fix

---

QMigrate/core/model.py

Fixed so that _select_station() will return the array containing the station the user has requested

fix(core/model.py): _select_station fix

---

QMigrate/core/model.py

fix(core/model.py): more _select_station fixes

---

QMigrate/signal/scan.py

column names are renamed
Gaussian_X, Gaussian_Y... -> LocalGaussian_X, LocalGaussian_Y...
Covariance_X, Covariance_Y... -> GlobalCovariance_X, GlobalCovariance_Y
This is to clarify the meaning of these values in the .event output
files.
Closes issue #18

style(signal/scan.py): rename location columns

---

QMigrate/signal/scan.py

Change how coalescence values are saved to mSEED format. Previously,
the values were multiplied by a factor of 1e8 then cast to np.int32.
This would cause overflow issues for coalescence values in excess of
21.474 (feasible values). Now the values are multiplied by a factor of
1e5 and values that would cause an overflow (those in excess of 21474.)
are saturated to that value before being cast to np.int32. Also removed
the redundant use of pandas in the write function.
Closes issue #17

fix(signal/scan.py): np.int32 overflow fix

---

QMigrate/core/model.py
QMigrate/signal/scan.py

Perform some minor code maintenance and reformat the terminal outputs.

Terminal output

---

QMigrate/signal/scan.py

Increase data range fed to the curve_fit() function: add 1 sample at either
end (so one sample point below the exceedence threshold is included), and
fix issue that previously one sample was missing from the t_max end of the
range due to an indexing error.

fix(signal/scan.py): Amend gaussian pick search window.

---

QMigrate/core/model.py
QMigrate/io/mseed.py
QMigrate/signal/scan.py

Add magic method for object representations when the python inbuilt
methods str and print are called on the objects. The outputs provide
useful information on the objects and their parameters.
Closes issue #2

feat(scan;model;mseed): added __str__ methods

---

QMigrate/signal/scan.py

Remove _gaussian_coalescence function and perform some minor code
cleanup. This function is no longer needed.

chore(signal/scan.py): deprecate functions

---

QMigrate/io/quakeio.py
QMigrate/signal/scan.py

Move SeisOutFile to io module and perform some renaming. This change is
entirely internal and tested, it should not affect end user usage.

refactor(signal/scan.py): move SeisOutFile

---

QMigrate/io/mseed.py
QMigrate/signal/scan.py

Fix floating point rounding error when calculating the number of samples
in the MSEED data traces between two times

fix(io/mseed.py): floating point error

---

QMigrate/signal/scan.py
example_running_scripts/detect.py
example_running_scripts/locate.py

Fix parameter name in data.path_structure() call.
path_type -> archive_format

fix(examples): parameter name fix

---

README.md

Remove link to unfinished wiki. Update readme text.

docs(README.md): Update readme

---

QMigrate/io/scanmseed.py
QMigrate/io/triggered_events.py
QMigrate/plot/trigger.py
QMigrate/signal/trigger.py

A series of commits in which the issues outlined in Issue #67 are addressed:
1 - split the internal workings of trigger into several stages to improve clarity 7129ede1a9b8dc58ed7d88588f68527997214392
2 - Batch trigger over Julian days 74761ae83c3d66f51cefd7ef3e87f91446a5d17f
3 - Fix a bug concerning the merging of candidate events 71b34253867079613495179b5cd866cb0a761f3d

Batch trigger

---

QMigrate/signal/local_mag/__init__.py
docs/submodules/QMigrate.signal.local_mag.rst
examples/template_scripts/locate.py

A page for the `QMigrate.signal.local_mag` submodule is added to the docs, and the module `__init__.py` is updated to feature a warning it is still a work-in-progress in https://github.com/QuakeMigrate/QuakeMigrate/commit/7f5ed2a8ce1f511c16fdf70eac3bbe8171d15a8c. The locate template script is updated to use an `AttribDict` to specify the local_mag parameters (https://github.com/QuakeMigrate/QuakeMigrate/commit/2e255d33ea626fd9c3cd16644dc9e48226f0f550).
Ubuntu 18.04

LocalMag tweaks.

---

setup.py

Update setup.py packages to include the new 'local_mag' package and the moving of the 'io.export' package to 'export. This was causing an issue on install.

fix: Update setup.py packages

---

README.md
docs/index.rst
docs/installation.rst
docs/submodules/quakemigrate.signal.rst

Update OS support on landing page. Also fix a couple of typos, add in
the documentation for the local magnitudes module.
Add our first (!!) badge - documentation.

docs: Update OS support on landing page

---

quakemigrate/io/scanmseed.py
quakemigrate/signal/scan.py

To implement fixes for two bugs which have been discovered related to running detect / locate. See commit messages for full details.
Ubuntu 18.04

FIX: Minor bugfixes in detect / locate

---

docs/installation.rst
quakemigrate.yml
quakemigrate/io/event.py
quakemigrate/lut/lut.py
quakemigrate/plot/event.py
quakemigrate/plot/phase_picks.py
quakemigrate/plot/trigger.py
requirements.txt
setup.py

To address the issues arising from the recent pandas release (1.1), which made some changes to address issues arising from the recent matplotlib release (3.3).
Also iron out some minor issues with the installation process guide.
Ran the install with the version pins, as well as testing whether pandas 1.1 + matplotlib 3.3 worked (it did not)
Ubuntu 18.04

Fix install issues

---

.gitignore
docs/installation.rst
environment.yml
pyproject.toml
quakemigrate/export/to_mfast.py
quakemigrate/io/data.py
quakemigrate/lut/create_lut.py
quakemigrate/util.py
requirements.txt
tests/test_util.py

To address a couple of minor bugs highlighted by recently submitted Issues.
#144 
#137 
#134 
- skfmm error tested with a modified dike_intrusion_lut where the grid was first left as-is ie not including all stations; then modified so that it did include all stations. All worked as intended.
- new merge strategy tested by adding a second copy of `FLUR_E.m` for the `Volcanotectonic_Iceland` example, with encoding changed to `FLOAT64`, meaning it would suffer from the failed merged scenario encountered in #137 . All worked as intended: error message highlighting the errant channel, but migration continued successfully using all unaffected data.
- to_mfast checked by applying this to the outputs from the …

FIX: more minor bug fixes addressing the list of current Issues

---

.github/workflows/run_tests.yml
pyproject.toml
quakemigrate/util.py

This PR implements a GitHub Action the runs the QuakeMigrate examples, assesses the code coverage these examples provide, and runs the benchmark comparison test. The Action is triggered by any of the following:
- Pushes to branches prefixed with:
- `feature/`
- `bugfix/`
- `patch/`
- `tests/`
- Pull requests where the target branch is either:
- `master`
- or is prefixed with `version/`
- The publication of a release
Tests are run for Python versions 3.8, 3.9, 3.10, and 3.11. Currently these tests are only run on the latest Ubuntu operating system—it would likely be wise to extend this to at least macOS, if not Windows as well (though we would have to find a solution to the NonLinLoc install issue with Windows. I have not yet tried to install NonLinLoc via the Cmake build system now …

Add GitHub workflow for testing/code coverage assessment

---

CHANGES.md
pyproject.toml

Bump version and add changes to CHANGES.md.

:wrench: Bump version to v1.0.3

---

pyproject.toml

Bump version number in `pyproject.toml` file to 1.2.0 (since all `version/` branches are protected).

:bookmark_tabs: bump version to v1.2.0 EOM
