QuakeMigrate/QuakeMigrate

.git-message-template

stripped out the redundant text from the commit template

style(commit-template): update template format

---

QMigrate/core/model.py

The reading of the velocity model was incorrectly assuming that there
was a header line in the input file. Optional argument added to function
that allows the user to specify whether the velocity model file has a
header line or not.

fix(core/model.py): velocity model input headers

---

QMigrate/signal/scan.py

Add a simple test to check if a given trace contains no data - if so, it
is simply skipped.
Closes issue #26

fix(signal/scan.py): plot_coa_trace RunTimeWarning

---

QMigrate/io/mseed.py

Fix issue in mseed reading in _load_from_path() when trying to read over
the yearline. Previously the code compared julian days, which causes
issues when comparing between December 31st and January 1st of the
following year (365/6 !< 1). Now simply compare UTCDateTime objects
directly and use the inbuilt comparison operator between them.

fix(io/mseed.py): fix read error over yearline

---

QMigrate/signal/scan.py

If the timespan for detect was not an integer multiple the timstep, the final
timestep was being missed off as the endtime was seen as a strict limit
(in a while st + x < et loop). To rectify this problem, we now take the
integer ceiling of (et - st) / time_step and for loop this many times.

fix(signal/scan.py): final timestep

---

QMigrate/io/mseed.py

Fix the test for generating the iterator that reads mseed files. Should
now function as expected and correctly read data over daylines.

fix(io/mseed.py): handle daylines

---

QMigrate/io/quakeio.py
QMigrate/plot/quakeplot.py
QMigrate/signal/scan.py

Restructure the output directory to make them easier to navigate. Now
you specify the output directory and a run name, and it will spawn a new
directory with the following structure:
run
|_events
|_logs
|_mseed
|_picks
|_summaries
|_traces
|_videos
|_run.scnmseed file
May require relabelling of detect runs performed prior to 6/6/2018.

feat(io;scan;plot): Output directory restructure

---

QMigrate/io/quakeio.py
QMigrate/plot/triggered_events.py
QMigrate/signal/scan.py
example_running_scripts/locate.py

Added a feature such that locate can be run with a start time
and end time (as was the default before) or that you can pass a
filename through locate. The locate.py script in the example running
scripts directory has also been updated.
New locate function call is
def locate(fname=None, start_time=None, end_time=None):

feat(scan.py): Added the flexibility to choose an input file for locate

---

QMigrate/plot/triggered_events.py
QMigrate/signal/trigger.py
example_running_scripts/trigger.py

Added a feature to the existing trigger framework allowing a user to use
a dynamic trigger threshold. The dynamic threshold is defined as some
multiple of the Median Absolute Deviation (MAD) within a given chunk of
data. Essentially the algorithm is defining a threshold above which only
significant outliers will exist, which we treat as a seismic event.
This update has been tested on a small chunk of Borneo data and the
example trigger.py script has been updated to demonstrate how the dynamic
threshold can be toggled and configured.
For more details, read the wikipedia page on Median Absolute Deviation
https://en.wikipedia.org/wiki/Median_absolute_deviation.
Updated instances of <str>.format() to use f-strings (where appropriate)

feat(trigger): Added dynamic triggering

---

QMigrate/signal/scan.py

Fix the event location being written to the .event files. Previously it
was incorrectly using the transformation going from the Cartesian grid
space to the geographical space on the indices which corresponded to the
event location. Now correctly using the index2coord transformation!
Any events previously located using the version of QuakeMigrate on the
development branch will have incorrect event locations and will need to
be relocated.

fix(locate): Fix event location output

---

QMigrate/lut/create_lut.py

Ensure the specified path is converted to a pathlib.Path object at the
top of the read_nlloc function, and converted back to a str when opened.

fix(read_nlloc): Usage of pathlib

---

.gitignore
QMigrate/lut/create_lut.py
QMigrate/signal/scan.py
QMigrate/signal/trigger.py
QMigrate/util.py
examples/Icequake_Iceland/iceland_detect.py
examples/Icequake_Iceland/iceland_locate.py
examples/Icequake_Iceland/iceland_lut.py
examples/Icequake_Iceland/iceland_trigger.py
examples/Icequake_Iceland/icequakes_iceland.ipynb
examples/Icequake_Rutford/icequakes_rutford.ipynb
examples/Icequake_Rutford/rutford_detect.py
examples/Icequake_Rutford/rutford_locate.py
examples/Icequake_Rutford/rutford_lut.py
examples/Icequake_Rutford/rutford_trigger.py

Made multiple fixes as a result of feedback from a user, namely with the
function that reads NLLoc traveltime tables:
Fixed projections used in NLLoc read function. Now correctly passes the
parameters needed for the lambert conformal conic projection and the
transverse mercator projection.
Improved code readability in the create_lut.py file, primarily by using
fstrings.
Added a catch for if a user tries to use nonsensical start/end times
(i.e. a start time after the end time).

chore: NLLoc read fixes and more

---

QMigrate/signal/onset/onset.py
QMigrate/signal/onset/staltaonset.py
QMigrate/signal/pick/gaussianpicker.py

Cut the final explicit tie between STALTAOnset and GaussianPicker - the
interface is now fully abstracted such that users can use the GaussianPicker
module with custom Onsets.
- Added a gaussian_halfwidth method to the Onset base class that will raise an
error if the user tries to use the GaussianPicker without implementing that
part of the interface.
- Added a gaussian_halfwidth method to the STALTAOnset class that takes a
phase argument and returns the phase-relevant short-term average window
length (in terms of samples).
Please state the systems on which you have tested this change.

refactor: Finalise interface abstraction for STALTAOnset and GaussianPicker

---

quakemigrate/signal/pick/gaussianpicker.py

This PR fixes the bug described in https://github.com/QuakeMigrate/QuakeMigrate/issues/98 where the S / P picks returned by the gaussianpicker can be outside the pick windows, and therefore potentially in the wrong order.
A check for this was implemented previously in https://github.com/QuakeMigrate/QuakeMigrate/commit/da3b907ea6a0ee1f695700c7430ace779f63cd0a , but using the wrong index for the comparison.
https://github.com/QuakeMigrate/QuakeMigrate/issues/98
Ubuntu 18.04

[FIX] gaussianpicker.py - Fix check that picktime is inside picking window

---

quakemigrate/io/triggered_events.py
quakemigrate/util.py

Catch and handle (by means of an explicit error message) an issue whereby the user might set an invalid run name or time period for locate, but the script would crash with a fairly impenetrable error.
All previous behaviour identical, now simply checks if any suitable triggered events files were found during the while loop. If not, raise the error. Perhaps it would be worth catching this and printing something neater before exiting the script, but the net effect is the same.
Tested by providing an invalid run name and an invalid time period. An invalid time period is one for which there is no overlap with the time period for which there exists TriggeredEvents.csv files.
Ubuntu 20.04

fix(locate): catch reading triggered events issue

---

quakemigrate/io/data.py
quakemigrate/signal/onsets/stalta.py
quakemigrate/util.py

Previously when data was upsampled during resampling (e.g. if going from raw data sampling rate of 40 Hz to an onset function sampling rate of 50 Hz), no check was made that the start and endtimes of the data read from the archive exactly matched the start and endtimes requested (which are calculated assuming the data being read is at the onset function sampling rate, or a multiple if it). In many cases this would not be the case, leading to this data being needlessly discarded.
In this PR this bug is fixed, along with:
* Adding a couple more options to `data.check_availability()` to explicitly check that the data is at the correct sampling rate, and an option to more strictly check it covers the requested timespan (by checking the start and endtimes, not just the number of samples).
* …

[FIX]: Fix resampling/upsampling bug; more explicit handling of data timing.

---

quakemigrate/io/cut_waveforms.py
quakemigrate/signal/local_mag/amplitude.py

To fix two bugs, and alter the handling of PickOrderException's during amplitude measurement:
1. Handle amplitude measurements outside the frequency range where the filter gain is defined (possible due to the very approximate estimate of the frequency of the peak-to-peak amplitude measurement)
2. Correct the handling of ResponseNotFoundError's during output of real or Wood-Anderson simulated cut waveforms / add handling for the AttributeError raised if a response inventory hasn't been provided.
3. Emit a warning if a PickOrderException occurs during amplitude measurement, instead of raising.
N/A
(1) Tested on data which had initially exposed these issues (Askja 2007-2020 dataset), and (2) tested on the dike example with mags switched on/off and response inventory (not) provided.
Ubuntu …

FIX: Minor bug fixes

---

quakemigrate/plot/trigger.py
quakemigrate/signal/trigger.py

To restore plotting of discarded events (filtered out by the optional `region` trigger kwarg).
#153 
Please state the systems on which you have tested this change.
- Operating System: macOS 11.4 Big Sur (x86_64)
- Python version: 3.9.16
- QuakeMigrate version: 1.0.1

FIX: Restore plotting of discarded events in Trigger

---

quakemigrate/lut/lut.py
quakemigrate/plot/phase_picks.py
quakemigrate/plot/trigger.py

Address an issue arising with the release of Matplotlib 3.8, wherein the syntax for defining shared axes was changed.
Every instance of `get_shared_x_axes`/`get_shared_y_axes` has been remapped to `ax.sharex` or `ax.sharey`.
This addresses the closed Pull Request #161.
No open issue, but previously acknowledged and discussed in Pull Request #161.
Tested on macOS Monterey v12.5.1. Python 3.11.5, matplotlib 3.8.0.
- `version/vX.X.X` if a new significant feature (discuss with developers)

Address issue with shared axes from Matplotlib 3.8

---

.github/workflows/run_tests.yml
quakemigrate/lut/lut.py
quakemigrate/plot/phase_picks.py
quakemigrate/plot/trigger.py
tests/test_benchmarks.py

An unreproducible bug (likely related to a floating point error) was causing the regular tests workflow to fail. A single pick time for a single event-station pair for one of the 26 events in the volcano-tectonic example was differing from the benchmarked pick time by 1 microsecond. This error did not always occur, and could not be reproduced independently on a macOS system nor Linux (Ubuntu 22.04). This suggests it is likely something specific to the machine used to run the workflow.
Our current ('band-aid') solution is to simply skip the benchmark comparison test for this specific event.
In addition to this test adjustment, we have added a stage to the test benchmarks workflow that, in the case of a test failure, an interactive tmate session is created to enable some minimal debugging. …

Add debug backdoor (tmate) and bypass root cause of test workflow failure

---

.github/workflows/build_wheels.yml

Bump of cibuildwheel version to fix #170  -- cibuildwheel 2.12.0 -> 2.16.5
As per https://github.com/pypa/cibuildwheel/issues/1740
#170 
(Tested on ubuntu 22.04; but really needs to run actions workflow to test)
- `version/vX.X.X` if a new significant feature (discuss with developers)

:wrench: Update cibuildwheels version to fix Windows wheel building

---

examples/Volcanotectonic_Iceland/get_dike_intrusion_data.py

Previously data was downloaded from each station sequentially in a loop; this instead makes use of the ability to list multiple stations in a single request. This should speed things up a little, and hopefully address #172
Initiated by failure of the automatic test run, seemingly due to timing out during data download for the VT-Iceland example. Hopefully by reducing requests we stay beneath any traffic limits, but this also provides a significant speed-up in the data download.
#172 - [Tests timing out on data acquisition from EarthScope stage](https://github.com/QuakeMigrate/QuakeMigrate/issues/172)
Ubuntu 22.04

:bug: Single client request for all stations

---

.github/workflows/run_tests.yml
codecov.yml

This PR will fix an issue with our coverage reports, which were failing to be properly parsed by CodeCov. The paths in the .xml report were absolute paths to the site-packages directory on the run machine, rather than relative to the package top-level (`quakemigrate`).
Add a codecov.yml file that should adjust these paths when sending the report. Also added the tests for specific parts of the package (under `tests/`) to the coverage report.
No relevant issue.
This PR does not change the source code at all. The GitHub Action for running our tests was successful and the coverage report was correctly parsed by CodeCov.
macOS 12.5.1 (M1 chip)
- `version/vX.X.X` if a new significant feature (discuss with developers)

Fix coverage reporting via CodeCov

---

CHANGES.md
pyproject.toml
quakemigrate/signal/trigger.py

Address a bug in Trigger caused by a deprecated (renamed) function within `numpy` (#187).
#187 
Ubuntu 22.04 / Python 3.12.5 / AMD Epyc
- [-] Any new features or fixed regressions are covered by new tests.
- [-] Any new or changed features are fully documented.

FIX: Replace deprecated (renamed) function within `numpy` (#187).

---

CHANGES.md
quakemigrate/io/scanmseed.py
quakemigrate/signal/scan.py

In instances when no data pass the criteria for a given timestep (or don't exist in the archive), an empty portion of data is added to the `ScanMSEED` object, equal in length to the timestep. There was a small bug, a hangover from other changes to how the timestep is handled bundled as part of v1.2.0, that meant an additional sample was added to this empty section. Previously this sample had been removed when this block was appended to the running `ScanMSEED` object. Since this was no longer removed, this bug led to multiple traces with a 1 sample overlap in the `ScanMSEED` object that could not be simply merged. This PR fixes this.
Ran this with a period of time where all data did not pass the selection criteria for the first timestep of the day (i.e., there was no waveform data for the …

Fix small bug with empty ScanMSEED objects

---

.github/workflows/build_wheels.yml

Update PyPI publish action from v1.9.0 to v1.12.4, which should handle issues with package metadata that was causing the publish workflow to fail.
None
No changes to codebase, so tests still pass.
Not tested, as this is run as a GitHub Action.
- `version/vX.X.X` if a new significant feature (discuss with developers)

:bug: update PyPI publish action

---

quakemigrate/__init__.py

Use of `pkg_resources` now triggers a `UserWarning` from `setuptools` - this PR switches to instead using `importlib.metadata.version` to populate the `__version__` attribute.
N/A
With the currently available version of `setuptools` importing any part of the `quakemigrate` package would result in this `UserWarning`. With this change the warning is no longer shown (and `quakemigrate.__version__` still returns the expected `1.2.0`).
- Note: I am currently receiving a LUT-related test failure, but this was seen both before and after this change, and is not relevant.
Please state the systems on which you have tested this change.
Apple M4 Pro / macOS 15.5 / Python 3.12.11

:wrench: Remove use of `pkg_resources`

---

quakemigrate/plot/trigger.py

As described in #204, `DataFrame.iteritems()` was removed in pandas 2.0, resulting in a failure within trigger plotting. This commit implements the discussed (and recommended) alternative `DataFrame.items()`. Also verified that there were no further instances of this function being used within the package.
#204 
Tested the `Icequake_Iceland` example with `trig.plot_all_stns = False` (as described by @hemmelig in #204) to verify that this change resolved the failure - and resulted in a trigger summary plot with station "SKG09" excluded.
- Note: I am currently receiving a LUT-related test failure, but this was seen both before and after this change, and is not relevant.
Apple M4 Pro / macOS 15.5 / Python 3.12.11

:bug: Remove use of removed `pandas.DataFrame.iteritems()`
